### ISSUE TITLE
Non-optional AdServices

### ISSUE THREAD

**Issue by Catar** [myTrackerSDK/mytracker-ios-spm#2]
Hello.
Your manifest here https://github.com/myTrackerSDK/mytracker-ios-spm/blob/main/Package.swift  requires AdServices.framework (non-optional requirement).
 AdServices is supported on iOS v 14.3+, though your manifest clearly states that you do support iOS 9+.

Expected behavior: either link AdServices optionally,  or raise minimum version to 14.3.
Observed behavior: crash on iOS 12.

**Comment by altk** [comment]
SPM doesn't allow optional linking.
At the next release we remove the dependency and provide workaround how to resolve it.
At the current release you could add the dependency as weak(optional) to you target.

**Comment by altk** [comment]
Fixed at release 3.0.4
