### ISSUE TITLE
Не проходит review из-за PrivacyInfo

### ISSUE THREAD

**Issue by matpaul** [myTrackerSDK/mytracker-ios-spm#6]
Версия: 3.1.9

ITMS-91064: Invalid tracking information:
 A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/MyTrackerSDK.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by aserrr** [comment]
исправим в ближайшем релизе

**Comment by aserrr** [comment]
выпустили 3.1.10
